
Workflow initiated on 06/03/19 at 18:00

Setting the Environment
determined the timestamp to download: 2019060300
Looks like you already have file structure for this timestep, lets see what we need to fill in.

Starting GFS Grib Downloads for hispaniola
There is no download folder, you must have already processed them. Skipping download stage.

Starting to process the GFS gribs into 24 hour files
There is no gribs folder, you must have already run this step. Skipping conversions

Resampling the rasters for hispaniola
There is no tiffs folder. You must have already resampled them. Skipping resampling

Doing Zonal Statistics on hispaniola

starting zonal statistics for file gfs_apcp_2019060300_hrs000-024_resampled.tif
writing the statistics for this file to the dataframe
done

starting zonal statistics for file gfs_apcp_2019060300_hrs024-048_resampled.tif
writing the statistics for this file to the dataframe
done

starting zonal statistics for file gfs_apcp_2019060300_hrs048-072_resampled.tif
writing the statistics for this file to the dataframe
done

starting zonal statistics for file gfs_apcp_2019060300_hrs072-096_resampled.tif
writing the statistics for this file to the dataframe
done

starting zonal statistics for file gfs_apcp_2019060300_hrs096-120_resampled.tif
writing the statistics for this file to the dataframe
done

starting zonal statistics for file gfs_apcp_2019060300_hrs120-144_resampled.tif
writing the statistics for this file to the dataframe
done

starting zonal statistics for file gfs_apcp_2019060300_hrs144-168_resampled.tif
writing the statistics for this file to the dataframe
done

done with zonal statistics, writing to a csv file
deleting the resampled tiffs directory

Processing the netCDF files
There are 7 compatible files.
Preparing the reference file
Working on file 2019060300_048.nc
Working on file 2019060300_168.nc
Working on file 2019060300_072.nc
Working on file 2019060300_120.nc
Working on file 2019060300_096.nc
Working on file 2019060300_024.nc
Working on file 2019060300_144.nc
Finished File Conversions

Writing a new ncml file for this date
Wrote New .ncml

Generating a new color scale csv for the gfs results
Internal Server Error: /apps/ffgs/runWorkflow/
Traceback (most recent call last):
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/rileyhales/tethys/src/tethys_apps/tethysapp/ffgs/controllers.py", line 99, in run_workflow
    new_colorscales(wrksppath, region[1], model[1])
  File "/Users/rileyhales/tethys/src/tethys_apps/tethysapp/ffgs/ffgsworkflow.py", line 396, in new_colorscales
    res_df = pd.read_csv(results)[['cat_id', 'mean', 'max']]
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/Users/rileyhales/tethys/miniconda/envs/tethys/lib/python3.6/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['max'] not in index"
"GET /apps/ffgs/runWorkflow/ HTTP/1.1" 500 118605
